site_name: 'Quix Docs'
site_description: 'Quix Developer Documentation. Includes documentation (tutorials, reference guides, how-tos, concepts) for Quix Platform, Quix Streams client library, and REST and websocket APIs.'
site_author: 'Quix.io'
site_url: 'https://quix.io/docs'

copyright: >
  Copyright &copy; 2020 - 2023 Quix Analytics, Ltd. â€“
  <a href="#__consent">Change cookie settings</a>

docs_dir: docs/
repo_name: quixio/quix-docs
repo_url: https://github.com/quixio/quix-docs
edit_uri: tree/dev/docs

nav:
  - 'Introduction': 'index.md'
  - 'Recent changes ðŸ”¥': 'platform/changes.md'
  - 'Quickstart ðŸš€': 'platform/quickstart.md'
  - 'What is Quix?': 'platform/what-is-quix.md'
  - 'Ingest data': 'platform/ingest-data.md'
  - 'Glossary': 'platform/glossary.md'
  - 'Contribute': 'contribute.md'
  - 'Quix Tour': 
    - 'Overview': 'platform/quixtour/overview.md'
    - '1. Ingest': 'platform/quixtour/ingest-push.md'
    - '2. Process': 'platform/quixtour/process-threshold.md'
    - '3. Serve': 'platform/quixtour/serve-sms.md'
  - Platform:
    - 'How To':
      - 'Create a project': 'platform/how-to/create-project.md'
      - 'Project structure': 'platform/how-to/project-structure.md'
      - 'Create an application': 'platform/how-to/create-application.md'
      - 'Get Environment ID': 'platform/how-to/get-environment-id.md'
      - 'Get streaming token': 'platform/how-to/streaming-token.md'
      - 'Get personal access token (PAT)': 'platform/how-to/personal-access-token-pat.md'
      - 'Ingest from CSV': 'platform/how-to/ingest-csv.md'
      - 'Use replay service': 'platform/how-to/replay.md'
      - 'Use Jupyter notebooks': 'platform/how-to/jupyter-nb.md'
      - 'Develop web applications with Quix': 'platform/how-to/webapps.md'
      - 'Write to Quix with Node.js': 'platform/how-to/webapps/write.md'
      - 'Read from Quix with Node.js': 'platform/how-to/webapps/read.md'
      - 'Create a Dead Letter Queue': 'platform/how-to/create-dlq.md'
      - 'Deploy public services': 'platform/how-to/deploy-public-page.md'
      - 'Add environment variables': 'platform/how-to/environment-variables.md'
      - 'Testing using Quix data store': 'platform/how-to/testing-data-store.md'
      - 'Configure deployments': 'platform/how-to/yaml-variables.md'
    - 'Tutorials':
      - 'platform/tutorials/index.md'
      - 'Computer vision': 
        - platform/tutorials/computer-vision/index.md
        - '1. Get the project': platform/tutorials/computer-vision/get-project.md
        - '2. TfL camera feed': platform/tutorials/computer-vision/tfl-camera-feed.md
        - '3. Frame grabber': platform/tutorials/computer-vision/tfl-frame-grabber.md
        - '4. Object detection': platform/tutorials/computer-vision/object-detection.md
        - '5. Web UI': platform/tutorials/computer-vision/web-ui.md
        - '6. Other services': platform/tutorials/computer-vision/other-services.md
        - '7. Add service': platform/tutorials/computer-vision/add-service.md
        - '8. Summary': platform/tutorials/computer-vision/summary.md        
      - 'Chat sentiment analysis': 
        - platform/tutorials/sentiment-analysis/index.md
        - '1. Get the project': platform/tutorials/sentiment-analysis/get-project.md
        - '2. Try the UI': 'platform/tutorials/sentiment-analysis/try-the-ui.md'
        - '3. UI service': 'platform/tutorials/sentiment-analysis/ui-service.md'
        - '4. Sentiment analysis service': 'platform/tutorials/sentiment-analysis/sentiment-analysis-service.md'
        - '5. Twitch service': 'platform/tutorials/sentiment-analysis/twitch-service.md'
        - '6. Customize the UI': 'platform/tutorials/sentiment-analysis/customize-the-ui.md'
        - '7. Summary': 'platform/tutorials/sentiment-analysis/summary.md'
      - 'Real-time ML predictions':
        - 'platform/tutorials/data-science/index.md'
        - '1. Bicycle data': 'platform/tutorials/data-science/1-bikedata.md'
        - '2. Weather data': 'platform/tutorials/data-science/2-weatherdata.md'
        - '3. Data views': 'platform/tutorials/data-science/3-data.md'
        - '4. Get training data': 'platform/tutorials/data-science/4-train.md'
        - '5. Run the model': 'platform/tutorials/data-science/5-run.md'
        - '6. Conclusion': 'platform/tutorials/data-science/6-conclusion.md'
      - 'Real-time ML pipelines':
        - platform/tutorials/train-and-deploy-ml/index.md
        - 'Create your data': 'platform/tutorials/train-and-deploy-ml/create-data.md'
        - 'Import data into Jupyter': 'platform/tutorials/train-and-deploy-ml/import-data.md'
        - 'Train your ML model': 'platform/tutorials/train-and-deploy-ml/train-ml.md'
        - 'Deploy your ML model': 'platform/tutorials/train-and-deploy-ml/deploy-ml.md'
        - 'Conclusion': 'platform/tutorials/train-and-deploy-ml/conclusion.md'
      - 'Real-time event detection':
        - 'platform/tutorials/event-detection/index.md'
        - '1. Data acquisition': 'platform/tutorials/event-detection/data-acquisition.md'
        - '2. Event detection': 'platform/tutorials/event-detection/crash-detection.md'
        - '3. Demo UI': 'platform/tutorials/event-detection/crash-detection-ui.md'
        - '4. Conclusion': 'platform/tutorials/event-detection/conclusion.md'
      - 'RSS Processing': 'platform/tutorials/rss-tutorial/rss-processing-pipeline.md'
      - 'Currency Alerting': 'platform/tutorials/currency-alerting/currency-alerting.md'
      - 'Data Stream Processing': 'platform/tutorials/data-stream-processing/data-stream-processing.md'
      - 'Slack Alerting': 'platform/tutorials/slack-alerting/slack-alerting.md'
      - 'No code sentiment analysis': 'platform/tutorials/nocode-sentiment/nocode-sentiment-analysis.md'
      - 'MATLAB and Simulink': 'platform/tutorials/matlab/matlab-and-simulink.md'
    - 'Code Samples': 'platform/samples/samples.md'
    - 'Integrations':
      - 'Kafka':
        - 'Confluent': 'platform/integrations/kafka/confluent-cloud.md'   
    - 'Connectors':
      - platform/connectors/index.md
#ConnectorsGetInsertedHere
    - 'Troubleshooting': 'platform/troubleshooting/troubleshooting.md'
    - 'Security': 'platform/security/security.md'
    - 'MLOps': 'platform/MLOps.md'
#  - 'Client Library': '!import https://github.com/quixio/quix-streams?branch=main'
  - API:
    - 'Intro': 'apis/intro.md'
    - 'Prerequisites': 'apis/prerequisites.md'
    - 'API References': 'apis/api-references.md'
    - 'HTTP requests': 'apis/http-requests.md'
    - 'Set up SignalR': 'apis/signalr.md'
    - 'Streaming Writer API': 
      - 'apis/streaming-writer-api/index.md'
      - 'Create a new Stream': 'apis/streaming-writer-api/create-stream.md'
      - 'Add Stream metadata': 'apis/streaming-writer-api/stream-metadata.md'
      - 'Send Parameter data': 'apis/streaming-writer-api/send-data.md'
      - 'Send an Event': 'apis/streaming-writer-api/send-event.md'
    - 'Streaming Reader API': 
      - 'apis/streaming-reader-api/index.md'
      - 'Reading data': 'apis/streaming-reader-api/reading-data.md'
      - 'Subscription and events': 'apis/streaming-reader-api/subscriptions.md'
    - 'Portal API': 
      - 'apis/portal-api/index.md'
    - 'Query API': 
      - 'apis/query-api/index.md'
      - 'Paged streams': 'apis/query-api/streams-paged.md'
      - 'Filtered streams': 'apis/query-api/streams-filtered.md'
      - 'Streams with models': 'apis/query-api/streams-models.md'
      - 'Raw data': 'apis/query-api/raw-data.md'
      - 'Aggregate data by time': 'apis/query-api/aggregate-time.md'
      - 'Aggregate data by tags': 'apis/query-api/aggregate-tags.md'
      - 'Tag filtering': 'apis/query-api/filter-tags.md'

plugins:
  - multirepo:
      cleanup: true
  - search:
      separator: '[\s\-\.]' 
  - social:
      cards_layout_dir: layouts
      cards_layout: custom 
  - glightbox
  - redirects:
      redirect_maps:
        'sdk-intro.md': 'client-library-intro.md'
        'platform/intro.md': 'platform/what-is-quix.md'
        'sdk/quickstart.md': 'client-library/quickstart.md'
        'sdk/kafka.md': 'client-library/kafka.md'
        'sdk/features/streaming-context.md': 'client-library/features/streaming-context.md'
        'sdk/features/builtin-buffers.md': 'client-library/features/builtin-buffers.md'
        'sdk/features/data-frames.md': 'client-library/features/data-frames.md'
        'sdk/features/message-splitting.md': 'client-library/features/message-splitting.md'
        'sdk/features/data-serialization.md': 'client-library/features/data-serialization.md'
        'sdk/features/multiple-data-types.md': 'client-library/features/multiple-data-types.md'
        'sdk/features/checkpointing.md': 'client-library/features/checkpointing.md'
        'sdk/features/horizontal-scaling.md': 'client-library/features/horizontal-scaling.md'
        'sdk/connect.md': 'client-library/connect.md'
        'sdk/app-management.md': 'client-library/app-management.md'
        'sdk/publish.md': 'client-library/publish.md'
        'sdk/subscribe.md': 'client-library/subscribe.md'
        'sdk/process.md': 'client-library/process.md'
        'sdk/state-management.md': 'client-library/state-management.md'
        'sdk/versionmigration.md': 'client-library/versionmigration.md'
        'sdk/using.md': 'client-library/using.md'
        'sdk/introduction.md': 'client-library-intro.md'
        'platform/tutorials/imageProcessing/imageProcessing.md': 'platform/tutorials/computer-vision/index.md'
        'platform/tutorials/image-processing/connect-video-tfl.md': 'platform/tutorials/computer-vision/tfl-camera-feed.md'
        'platform/tutorials/image-processing/index.md': 'platform/tutorials/computer-vision/index.md'
        'platform/tutorials/train-and-deploy-ml/train-ml-model.md': 'platform/tutorials/train-and-deploy-ml/index.md'
        'platform/tutorials/data-science/data-science.md': 'platform/tutorials/data-science/index.md'
        'platform/tutorials/eventDetection/index.md': 'platform/tutorials/event-detection/index.md'
        'platform/tutorials/quick-start/quick-start.md': 'platform/quickstart.md'
        'platform/how-to/use-sdk-token.md': 'platform/how-to/streaming-token.md'
        'platform/how-to/connect-to-quix.md': 'platform/ingest-data.md'
        'apis/data-catalogue-api/intro.md': 'apis/query-api/index.md'
        'apis/streaming-reader-api/intro.md': 'apis/streaming-reader-api/index.md'
        'apis/streaming-writer-api/intro.md': 'apis/streaming-writer-api/index.md'
        'apis/query-api/intro.md': 'apis/query-api/index.md'
        'apis/portal-api.md': 'apis/portal-api/index.md'
        'apis/index.md': 'apis/intro.md'
        'platform/definitions.md': 'platform/glossary.md'
        
theme:
  name: 'material'
  custom_dir: overrides
  features:
    - content.code.copy
  # TODO
  #custom_dir: 'theme'
  favicon: 'assets/favicon.ico'
  
  palette: 
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  features:
  - navigation.instant     # Instant loading pages.
  - navigation.sections    # Render top sections as groups.
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  - navigation.indexes     # Documents can be directly attached to sections
  - search.highlight       # Search will highlight the searched word(s) on the page.*
  - search.share           # Adds an option to share a search query link.*
  - search.suggest         # Search will suggest the likeliest completion for a word.*
  - content.tabs.link
  - content.code.annotate  # code annotations
  - content.action.view    # view page source
  - content.code.copy
  
  icon:
    logo: 'material/library'
    repo: 'material/library'
  

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/quix.js
  - javascripts/feedback.js
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/quixio/quix-docs'
    - icon: 'fontawesome/brands/slack'
      link: 'https://quix.io/community'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/quix_io'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCrijXvbQg67m9-le28c7rPA'
  analytics:
    provider: google-tag-manager
    property: GTM-55L66N3
  posthog:
    host: https://eu.posthog.com
    key: phc_UyQcafs2J7OUQEwJrmejeb0vCIdA9i9vYz66suPshix
  hotjar:
    id: 2437577
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      posthog: Posthog
  
  #alternate:
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details:
  - pymdownx.highlight:
      anchor_linenums: true
