site_name: 'Quix Docs'
site_description: 'Quix Docs'
site_author: 'Quix.io'
site_url: 'https://docs.quix.io'

copyright: >
  Copyright &copy; 2020 - 2022 Quix â€“
  <a href="#__consent">Change cookie settings</a>

docs_dir: docs/
repo_name: quixai/quix-docs-dev
repo_url: https://github.com/quixai/quix-docs
edit_uri: tree/dev/docs/
nav:
  - Intro: 'index.md'
  - 'Quick Start': 'platform/tutorials/quick-start.md'
  - Platform:
    - 'What is Quix?': 'platform/intro.md'
    - 'Definitions': 'platform/definitions.md'
    - 'How To':
      - 'Get Workspace ID': 'platform/how-to/get-workspace-id.md'
      - 'Use SDK token': 'platform/how-to/use-sdk-token.md'
      - 'Use Jupyter notebooks': 'platform/how-to/jupyter-nb.md'
      - 'Develop web applications with Quix': 'platform/how-to/webapps.md'
      - 'Write to Quix with NodeJs': 'platform/how-to/webapps/write.md'
      - 'Read from Quix with NodeJs': 'platform/how-to/webapps/read.md'
      - 'Create a Dead Letter Queue': 'platform/how-to/create-dlq.md'
    - 'Tutorials':
      - 'Image Processing': 'platform/tutorials/ImageProcessing.md'
      - 'Sentiment analysis': 'platform/tutorials/sentimentAnalysis.md'
      - 'No code sentiment analysis': 'platform/tutorials/nocode-sentiment-analysis.md'
      - 'RSS Processing': 'platform/tutorials/RSSProcessingPipeline.md'
      - 'Currency Alerting': 'platform/tutorials/currency-alerting.md'
      - 'Telemetry data': 'platform/tutorials/telemetry-data.md'
      - 'Train and deploy an ML model':
        - 'How to train an ML model': 'platform/tutorials/train-and-deploy-ml/train-ml-model.md'
        - 'Run ML model in realtime environment': 'platform/tutorials/train-and-deploy-ml/deploy-ml.md'
      - 'Data Science': 'platform/tutorials/data-science/data-science.md'
    - 'Code Samples': 'platform/samples/samples.md'
    - 'Troubleshooting': 'platform/troubleshooting/troubleshooting.md'
    - 'Security': 'platform/security/security.md'
  - SDK:
    - 'Introduction': 'sdk/introduction.md'
    - 'Kafka and Quix SDK': 'sdk/kafka.md'
    - 'Features overview':
      - 'Streaming context': 'sdk/features/streaming-context.md'
      - 'In-memory processing': 'sdk/features/in-memory-processing.md'
      - 'Built-in buffers': 'sdk/features/builtin-buffers.md'
      - 'Support for Data Frames': 'sdk/features/data-frames.md'
      - 'Message splitting': 'sdk/features/message-splitting.md'
      - 'Message compression': 'sdk/features/message-compression.md'
      - 'Data serialization': 'sdk/features/data-serialization.md'
      - 'Multiple data types': 'sdk/features/multiple-data-types.md'
      - 'Broker configuration': 'sdk/features/broker-configuration.md'
      - 'Checkpointing': 'sdk/features/checkpointing.md'
      - 'Horizontal scaling': 'sdk/features/horizontal-scaling.md'
      - 'Integrations': 'sdk/features/integrations.md'
      - 'Portability': 'sdk/features/portability.md'
    - 'Connect to Quix': 'sdk/connect.md'
    - 'Writing data': 'sdk/write.md'
    - 'Reading data': 'sdk/read.md'
    - 'Processing data': 'sdk/process.md'
    - 'State management': 'sdk/state-management.md'
    - 'Local environment':
      - 'Set up local environment': 'sdk/python-setup.md'
      - 'Set up docker environment': 'sdk/docker-setup.md'
  - API:
    - 'Data Catalogue API':
      - 'Introduction': 'apis/data-catalogue-api/intro.md'
      - 'Authenticate': 'apis/data-catalogue-api/authenticate.md'
      - 'Getting Swagger url': 'apis/data-catalogue-api/get-swagger.md'
      - 'Forming a request': 'apis/data-catalogue-api/request.md'
      - 'Paged streams': 'apis/data-catalogue-api/streams-paged.md'
      - 'Filtered streams': 'apis/data-catalogue-api/streams-filtered.md'
      - 'Streams with models': 'apis/data-catalogue-api/streams-models.md'
      - 'Raw data': 'apis/data-catalogue-api/raw-data.md'
      - 'Aggregate data by time': 'apis/data-catalogue-api/aggregate-time.md'
      - 'Aggregate data by tags': 'apis/data-catalogue-api/aggregate-tags.md'
      - 'Tag filtering': 'apis/data-catalogue-api/filter-tags.md'
    - 'Streaming Writer API':
      - 'Introduction': 'apis/streaming-writer-api/intro.md'
      - 'Authenticate': 'apis/streaming-writer-api/authenticate.md'
      - 'Getting Swagger url': 'apis/streaming-writer-api/get-swagger.md'
      - 'Forming a request': 'apis/streaming-writer-api/request.md'
      - 'Set up SignalR': 'apis/streaming-writer-api/signalr.md'
      - 'Create a new Stream': 'apis/streaming-writer-api/create-stream.md'
      - 'Add Stream metadata': 'apis/streaming-writer-api/stream-metadata.md'
      - 'Send Parameter data': 'apis/streaming-writer-api/send-data.md'
      - 'Send an Event': 'apis/streaming-writer-api/send-event.md'
    - 'Streaming Reader API':
      - 'Introduction': 'apis/streaming-reader-api/intro.md'
      - 'Authenticate': 'apis/streaming-reader-api/authenticate.md'
      - 'Set up SignalR': 'apis/streaming-reader-api/signalr.md'
      - 'Reading data': 'apis/streaming-reader-api/reading-data.md'
      - 'Subscription & Event reference': 'apis/streaming-reader-api/subscriptions.md'
    #- 'API Reference':
    #  - 'API V1': '!include ./api-docs/mkdocs.yml'
  # - Services:
  #   - Replay: '!include ./replay/mkdocs.yml'

plugins:
  - search:
      separator: '[\s\-\.]' 
  #- monorepo
  
theme:
  name: 'material'
  custom_dir: overrides
  # TODO
  logo: assets/Quix-docs-logo-header.svg
  #custom_dir: 'theme'
  #favicon: 'assets/images/favicon.png'
  
  palette: 
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  features:
  - navigation.instant     # Instant loading pages.
  - navigation.sections    # Render top sections as groups.
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  - search.highlight # Search will highlight the searched word(s) on the page.*
  - search.share     # Adds an option to share a search query link.*
  - search.suggest   # Search will suggest the likeliest completion for a word.*
  - content.tabs.link
  
  icon:
    logo: 'material/library'
    repo: 'material/library'
  
  # paid for option
  #admonition:
  #    note: 'octicons/tag-16'
  #    abstract: 'octicons/checklist-16'
  #    info: 'octicons/info-16'
  #    tip: 'octicons/squirrel-16'
  #    success: 'octicons/check-16'
  #    question: 'octicons/question-16'
  #    warning: 'octicons/alert-16'
  #    failure: 'octicons/x-circle-16'
  #    danger: 'octicons/zap-16'
  #    bug: 'octicons/bug-16'
  #    example: 'octicons/beaker-16'
  #    quote: 'octicons/quote-16'

extra_css:
  - stylesheets/extra.css
#extra_javascript:
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/quixai/quix-docs'
    - icon: 'fontawesome/brands/slack'
      link: 'https://quix.io/community'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/quix_io'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCrijXvbQg67m9-le28c7rPA'
  analytics:
    provider: google
    property: G-xxx #UA-173360929-3 #TODO enable when ready
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
          #https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#was-this-page-helpful
          #submitted ratings collected on GA

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true


# turn on for pretty cards when link shared on social etc.
# see https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#configuration
#  - social:
#      cards: true
#      cards_dir: assets/images/social
  #generator: true
  
  #manifest: manifest.webmanifest
  
  #alternate:
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  #- markdown.extensions.admonition:
  #- markdown.extensions.codehilite:
  #    guess_lang: false
  #- markdown.extensions.toc:
  #    permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  - pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  - pymdownx.highlight:
      anchor_linenums: true

  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  #- pymdownx.superfences
  #- pymdownx.tabbed:
  #- pymdownx.tasklist:
  #- pymdownx.tilde: