site_name: 'Quix Docs'
site_description: 'Quix Docs'
site_author: 'Quix.io'
site_url: 'https://quix.io'

copyright: >
  Copyright &copy; 2020 - 2022 Quix â€“
  <a href="#__consent">Change cookie settings</a>

docs_dir: docs/
repo_name: quixai/quix-docs
repo_url: https://github.com/quixai/quix-docs
edit_uri: tree/develop/docs/
nav:
  - Intro: index.md
  - Page2: page-2.md
  - API:
    - v1: '!include ./v1/mkdocs.yml'
  - Services:
    - Replay: '!include ./replay/mkdocs.yml'

theme:
  name: 'material'
  # TODO
  logo: assets/quix-logo.svg
  #custom_dir: 'theme'
  #favicon: 'assets/images/favicon.png'
  
  palette: 
  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    #scheme: 'slate'
    
    #primary: 'indigo'
    
    #accent: 'indigo'
    
  #font:
  #  text: 'Roboto'
  #  code: 'Roboto Mono'
  
  #language: 'en'
  
  #direction: 'ltr'
  
  features:
  # Announce
  #
  #- announce.dismiss # Adds a "X" button to dismiss a news banner/mark it as read.*
  
  # Header
  #
  #- header.autohide # Hide header when user scrolls past a specific point.
  
  # Navigation:
  #
  #- navigation.expand      # Expand all collapsable sections.
  - navigation.instant     # Instant loading pages.
  #- navigation.indexes     # Attach pages directly to Sections. Incompatible with "toc.integrate"
  - navigation.sections    # Render top sections as groups.
  #- navigation.tabs         # Render top sections as tabs at the top.
  #- navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  
  # Search
  #
  - search.highlight # Search will highlight the searched word(s) on the page.*
  - search.share     # Adds an option to share a search query link.*
  - search.suggest   # Search will suggest the likeliest completion for a word.*
  
  # Table of Contents
  #
  #- toc.integrate          # Include the TOC sections in the left navugation.
  
  icon:
    logo: 'material/library'
    repo: 'material/library'
  
  # paid for option
  #admonition:
  #    note: 'octicons/tag-16'
  #    abstract: 'octicons/checklist-16'
  #    info: 'octicons/info-16'
  #    tip: 'octicons/squirrel-16'
  #    success: 'octicons/check-16'
  #    question: 'octicons/question-16'
  #    warning: 'octicons/alert-16'
  #    failure: 'octicons/x-circle-16'
  #    danger: 'octicons/zap-16'
  #    bug: 'octicons/bug-16'
  #    example: 'octicons/beaker-16'
  #    quote: 'octicons/quote-16'

#extra_css:
#extra_javascript:
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/quixai/quix-docs'
    - icon: 'fontawesome/brands/slack'
      link: 'https://quix.io/community'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/quix_io'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCrijXvbQg67m9-le28c7rPA'
  analytics:
    provider: google
    property: G-XXXXXXXXXX #todo need docs ga code
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
          #https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#was-this-page-helpful
          #submitted ratings collected on GA

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true


plugins:
  - search:
      separator: '[\s\-\.]' 

# turn on for pretty cards when link shared on social etc.
# see https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#configuration
#  - social:
#      cards: true
#      cards_dir: assets/images/social
  #generator: true
  
  #manifest: manifest.webmanifest
  
  #alternate:
markdown_extensions:
  - admonition
  #- markdown.extensions.admonition:
  #- markdown.extensions.codehilite:
  #    guess_lang: false
  #- markdown.extensions.toc:
  #    permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  #- pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  - pymdownx.highlight:
      anchor_linenums: true

  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  - pymdownx.superfences
  #- pymdownx.tabbed:
  #- pymdownx.tasklist:
  #- pymdownx.tilde: