# Adding Workflow to Branch
name: Sync with Quix Docs Dev
on:
  workflow_dispatch:   # run manually
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 10  # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
      with:  # all args are optional
       upstream: quixai/quix-docs-dev
       branch:   dev
